variables:
  - name: _BuildConfig
    value: Release

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pr:
  autoCancel: false
  branches:
    include:
    - '*'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      clean: true
      path: s/ # "s" is the default when only one repo is checked out

    - template: /eng/common/templates/steps/prepare-testassets.yml

    - template: /eng/common/templates/steps/install-dotnet-sdks.yml

    - template: /eng/common/templates/steps/restore-and-build.yml

    - template: /eng/common/templates/steps/test-and-upload-results.yml

    - template: /eng/common/templates/steps/pack-and-upload.yml

  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true
      path: s/ # "s" is the default when only one repo is checked out

    - template: /eng/common/templates/steps/prepare-testassets.yml

    - template: /eng/common/templates/steps/install-dotnet-sdks.yml

    - template: /eng/common/templates/steps/restore-and-build.yml

    - template: /eng/common/templates/steps/test-and-upload-results.yml

  - job: macOS
    condition: eq(false, true) # disable macOS tests. See https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#notes-on-choosing-hosted-macos
    pool:
      vmImage: 'macOS-latest'
    steps:
    - checkout: self
      clean: true
      path: s/ # "s" is the default when only one repo is checked out

    - template: /eng/common/templates/steps/prepare-testassets.yml

    - template: /eng/common/templates/steps/install-dotnet-sdks.yml

    - template: /eng/common/templates/steps/restore-and-build.yml

    - template: /eng/common/templates/steps/test-and-upload-results.yml
