using Microsoft.Extensions.Primitives;

namespace Yarp.Extensions.Firewall.Configuration;

/// <summary>
/// Provides an implementation of IFirewallConfigProvider to support config being generated by code.
/// </summary>
/// <remarks>
/// Creates a new instance, specifying a revision id of the configuration.
/// </remarks>
/// <param name="rules"></param>
/// <param name="componentExtensions"></param>
/// <param name="revisionId"></param>
public sealed class InMemoryConfigProvider(IReadOnlyList<RouteFirewallConfig> rules, IDictionary<Type, object> componentExtensions, string revisionId) : IFirewallConfigProvider
{
    // Marked as volatile so that updates are atomic
    private volatile InMemoryConfig _config = new(rules, componentExtensions, revisionId);

    /// <summary>
    /// Creates a new instance.
    /// </summary>
    public InMemoryConfigProvider(IReadOnlyList<RouteFirewallConfig> rules, IDictionary<Type, object> componentExtensions) : this(rules, componentExtensions, Guid.NewGuid().ToString())
    {
    }

    /// <summary>
    /// Implementation of the IFirewallConfigProvider.GetConfig method to supply the current snapshot of configuration.
    /// </summary>
    /// <returns></returns>
    public IFirewallConfig GetConfig() => _config;

    /// <summary>
    /// Swaps the config state with a new snapshot of the configuration, then signales that the old one is outdated.
    /// </summary>
    public void Update(IReadOnlyList<RouteFirewallConfig> routeFirewalls, IDictionary<Type, object> componentExtensions)
    {
        var newConfig = new InMemoryConfig(routeFirewalls, componentExtensions);
        UpdateInternal(newConfig);
    }

    /// <summary>
    /// Swaps the config state with a new snapshot of the configuration, then signales that the old one is outdated.
    /// </summary>
    public void Update(IReadOnlyList<RouteFirewallConfig> routeFirewalls, IDictionary<Type, object> componentExtensions, string revisionId)
    {
        var newConfig = new InMemoryConfig(routeFirewalls, componentExtensions, revisionId);
        UpdateInternal(newConfig);
    }

    private void UpdateInternal(InMemoryConfig newConfig)
    {
        var oldConfig = Interlocked.Exchange(ref _config, newConfig);
        oldConfig.SignalChange();
    }

    /// <summary>
    /// Implementation of IFirewall config which is a snapshot of the current config state. The data for this class should be immutable.
    /// </summary>
    private class InMemoryConfig : IFirewallConfig
    {
        private readonly CancellationTokenSource _cts = new();

        public InMemoryConfig(IReadOnlyList<RouteFirewallConfig> routeFirewalls, IDictionary<Type, object> componentExtensions) : this(routeFirewalls, componentExtensions, Guid.NewGuid().ToString())
        {
        }

        public InMemoryConfig(IReadOnlyList<RouteFirewallConfig> routeFirewalls, IDictionary<Type, object> componentExtensions, string revisionId)
        {
            RouteFirewalls = routeFirewalls;
            ConfigurationExtensions = componentExtensions;
            RevisionId = revisionId;
            ChangeToken = new CancellationChangeToken(_cts.Token);
        }

        public string RevisionId { get; }

        public IReadOnlyList<RouteFirewallConfig> RouteFirewalls { get; }

        public IDictionary<Type, object> ConfigurationExtensions { get; }

        public IChangeToken ChangeToken { get; }


        internal void SignalChange()
        {
            _cts.Cancel();
        }
    }
}
