using Microsoft.Extensions.Primitives;

namespace Yarp.Extensions.Firewall.Configuration;

/// <summary>
/// Provides an implementation of IFirewallConfigProvider to support config being generated by code.
/// </summary>
public sealed class InMemoryConfigProvider : IFirewallConfigProvider
{
    // Marked as volatile so that updates are atomic
    private volatile InMemoryConfig _config;

    public InMemoryConfigProvider(IReadOnlyList<RouteFirewallConfig> rules, string geoIPDatabasePath) : this(rules, geoIPDatabasePath, Guid.NewGuid().ToString())
    {
    }

    public InMemoryConfigProvider(IReadOnlyList<RouteFirewallConfig> rules, string geoIPDatabasePath, string revisionId)
    {
        _config = new InMemoryConfig(rules, geoIPDatabasePath, revisionId);
    }

    public IFirewallConfig GetConfig() => _config;

    public void Update(IReadOnlyList<RouteFirewallConfig> routeFirewalls, string geoIPDatabasePath)
    {
        var newConfig = new InMemoryConfig(routeFirewalls, geoIPDatabasePath);
        UpdateInternal(newConfig);
    }

    public void Update(IReadOnlyList<RouteFirewallConfig> routeFirewalls, string geoIPDatabasePath, string revisionId)
    {
        var newConfig = new InMemoryConfig(routeFirewalls, geoIPDatabasePath, revisionId);
        UpdateInternal(newConfig);
    }

    private void UpdateInternal(InMemoryConfig newConfig)
    {
        var oldConfig = Interlocked.Exchange(ref _config, newConfig);
        oldConfig.SignalChange();
    }

    /// <summary>
    /// Implementation of IFirewall config, and is a snapshot of the current config state. Should be immutable
    /// </summary>
    private class InMemoryConfig : IFirewallConfig
    {
        private readonly CancellationTokenSource _cts = new();

        public InMemoryConfig(IReadOnlyList<RouteFirewallConfig> routeFirewalls, string geoIPDatabasePath) : this(routeFirewalls, geoIPDatabasePath, Guid.NewGuid().ToString())
        {
        }

        public InMemoryConfig(IReadOnlyList<RouteFirewallConfig> routeFirewalls, string geoIPDatabasePath, string revisionId)
        {
            RouteFirewalls = routeFirewalls;
            GeoIPDatabasePath = geoIPDatabasePath;
            RevisionId = revisionId;
            ChangeToken = new CancellationChangeToken(_cts.Token);
        }

        public string RevisionId { get; }

        public IReadOnlyList<RouteFirewallConfig> RouteFirewalls { get; }

        public string GeoIPDatabasePath { get; }

        public IChangeToken ChangeToken { get; }


        internal void SignalChange()
        {
            _cts.Cancel();
        }
    }
}
